# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jackson Kao Yee Tsung
title: Software Engineer
email: Jacksonkao97@gmail.com
website: https://github.com/Jacksonkao97

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: nope
github_username:  Jacksonkao
# stackoverflow_username: "00000001"
# dribbble_username: nope
facebook_username: Jacksonkao
# flickr_username: nope
#instagram_username: nope
linkedin_username: Jacksonkao
# xing_username: nope
# pinterest_username: nope
youtube_username: Jacksonkao
# googleplus_username: +nope
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/tempProfile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jackson kao and I'm a Software Engineer. Friendly, Passion, and quick adaptability undergraduate software engineering student seeking an internship position at your company. Experienced in team working, fast pace environment as well as well-developed version control knowledge. Aim to develop work experience and contribute successfully to the organization.
  
  I am most skilled in: <mark>Java</mark> and <mark>Playing video games</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Eu Yan Sang
        link: https://www.euyansang.com/
        sub_title: Salesperson
        caption: Jan 2016 - March 2016
        description: | # this will include new lines to allow paragraphs

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Manitoba
        caption: 2019 - present
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PSB acedemy
        caption: 2017 - 2018
        sub_title: Diploma in Infocomm Technology
        description: | # this will include new lines to allow paragraphs


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
          Due to Covid-19 happens during my education time, most of the time I spent at is my apartment. At first, I though that this is good to me cause I have more time to studying and playing video games with my friends.....but thanks to the different time zone between Canada and Malaysia, I'm been forced to become a single-player.
      - Watch Drama
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
