servers:
  - url: https://api.manitoba_intitutes.com/v1
openapi: 3.0.0
info:
  title: |-
    Manitoba Institutes API
  description: |-
    The Manitoba Institutes API allows users to get university and colleges information within Manitoba, 
    including the name of the university, the date of establish and the number of students in the university.
  version: 1.0.1
  
tags:
  - name: Info
    description: |-
      Everything about the institute.

paths:
  /institutes/json:
    get:
      tags: 
        - Info
      summary: |-
        Get university and college information
      description: |-
        City is the only paramater that is required.
      operationId: |-
        getInstituteInfo
      parameters:
        - in: query
          name: Name
          schema:
            type: string
          description: |-
            The name of the institution for which the user wants the information.
          required: false
        - in: query
          name: Public
          schema:
            type: boolean
          description: |-
            Pass **true** if user wants the list of all public institutions in Manitoba, or **false** for the list of private institutions.
          required: false
        - in: query
          name: City
          schema:
            type: string
          description: |-
            The name of the city for which the user wants the list of institutions.
          required: true
      responses:
        200:
          description: |-
            Request Successful
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      institute:
                        $ref: '#/components/schemas/Institute'
                      status:
                        type: string
        400:
          description: |-
            Bad request
          content:
            application/text:
              schema:
                oneOf:
                  - type: string
                    description: |-
                      Infomation does not exists.

components:
  schemas:
    Institute:
      type: object
      properties:
        name:
          type: string
          description: |-
            Name of the institution
        date_of_establishment:
          type: integer
          description: |-
            Date of establishment of the institution
        number_of_attendees:
          type: integer
          description: |-
            Number of attendees in the institution